Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically,
when increasing is False, the i-th output column is the input vector raised element-wise
to the power of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [1]:
import numpy as np
x = np.array([1, 2, 3, 5])
N = 3

In [2]:
output1 = np.vander(x)
print('NP Vander with Array only')
print(output1)

NP Vander with Array only
[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]


In [3]:
output2 = np.vander(x, N)
print('NP Vander with Array and N Values')
print(output2)

NP Vander with Array and N Values
[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [25  5  1]]


In [4]:
output3 = np.column_stack([x**(N-1-i) for i in range(N)])
print('NP Vander with Power (N-1-i)')
print(output3)

NP Vander with Power (N-1-i)
[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [25  5  1]]


In [5]:
output4 = np.vander(x, increasing=True)
print('NP Vander with Increasing True')
print(output4)

NP Vander with Increasing True
[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   5  25 125]]


In [6]:
output5 = np.vander(x, increasing=False)
print('NP Vander with Increasing False')
print(output5)

NP Vander with Increasing False
[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]
